create table employee (
	id INT,
	name VARCHAR(50),
	gender VARCHAR(50),
	salary VARCHAR(50),
	department VARCHAR(50)
);
insert into employee (id, name, gender, salary, department) values (1, 'Stanly Normington', 'Genderqueer', '5991.58', 'Engineering');
insert into employee (id, name, gender, salary, department) values (2, 'Haley Turvey', 'Female', '5980.06', 'Sales');
insert into employee (id, name, gender, salary, department) values (3, 'Ian Aberkirder', 'Male', '6272.99', 'Sales');
insert into employee (id, name, gender, salary, department) values (4, 'Haily Lovell', 'Female', '6161.87', 'Accounting');
insert into employee (id, name, gender, salary, department) values (5, 'Lilith Pomroy', 'Female', '7302.42', 'Legal');
insert into employee (id, name, gender, salary, department) values (6, 'Tiffani Leitch', 'Female', '5881.63', 'Support');
insert into employee (id, name, gender, salary, department) values (7, 'Arvin Boothman', 'Male', '7560.70', 'Product Management');
insert into employee (id, name, gender, salary, department) values (8, 'Olive Ropkins', 'Female', '8862.03', 'Support');
insert into employee (id, name, gender, salary, department) values (9, 'Cherey McCusker', 'Female', '7886.08', 'Accounting');
insert into employee (id, name, gender, salary, department) values (10, 'Kikelia Grutchfield', 'Female', '7707.18', 'Training');
insert into employee (id, name, gender, salary, department) values (11, 'Timmy Kupka', 'Male', '6911.83', 'Accounting');
insert into employee (id, name, gender, salary, department) values (12, 'Enrika Bushen', 'Female', '4358.24', 'Engineering');
insert into employee (id, name, gender, salary, department) values (13, 'Joshua Goodricke', 'Male', '4786.45', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (14, 'Gretna Broadfoot', 'Polygender', '6949.68', 'Business Development');
insert into employee (id, name, gender, salary, department) values (15, 'Khalil Deschelle', 'Male', '5208.29', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (16, 'Jason Goricke', 'Male', '8263.39', 'Legal');
insert into employee (id, name, gender, salary, department) values (17, 'Maggie Geraldo', 'Agender', '8028.62', 'Sales');
insert into employee (id, name, gender, salary, department) values (18, 'Phillida Calverley', 'Female', '6570.49', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (19, 'Milka Leadbitter', 'Female', '6767.31', 'Product Management');
insert into employee (id, name, gender, salary, department) values (20, 'Brannon Grogan', 'Male', '6754.49', 'Services');
insert into employee (id, name, gender, salary, department) values (21, 'Jerrilee Edensor', 'Genderfluid', '7449.97', 'Accounting');
insert into employee (id, name, gender, salary, department) values (22, 'Valenka Moggan', 'Female', '8900.84', 'Legal');
insert into employee (id, name, gender, salary, department) values (23, 'Pete Felderer', 'Male', '5074.10', 'Training');
insert into employee (id, name, gender, salary, department) values (24, 'Errol Robertelli', 'Male', '6045.07', 'Product Management');
insert into employee (id, name, gender, salary, department) values (25, 'Ezekiel Gozney', 'Male', '7543.81', 'Marketing');
insert into employee (id, name, gender, salary, department) values (26, 'Fran Viggars', 'Male', '4731.11', 'Engineering');
insert into employee (id, name, gender, salary, department) values (27, 'Roderigo Ebbitt', 'Male', '4724.40', 'Business Development');
insert into employee (id, name, gender, salary, department) values (28, 'Arch Cadge', 'Male', '5451.64', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (29, 'Aurel Bax', 'Polygender', '7016.22', 'Business Development');
insert into employee (id, name, gender, salary, department) values (30, 'Ebenezer Lightollers', 'Male', '7222.05', 'Services');
insert into employee (id, name, gender, salary, department) values (31, 'Lorena Bordes', 'Female', '5483.38', 'Business Development');
insert into employee (id, name, gender, salary, department) values (32, 'Arron Meardon', 'Male', '5940.89', 'Sales');
insert into employee (id, name, gender, salary, department) values (33, 'Yovonnda Brent', 'Female', '8878.94', 'Training');
insert into employee (id, name, gender, salary, department) values (34, 'Richmond Kennealy', 'Male', '4865.03', 'Business Development');
insert into employee (id, name, gender, salary, department) values (35, 'Loutitia Arnli', 'Female', '6217.87', 'Sales');
insert into employee (id, name, gender, salary, department) values (36, 'Josepha Meriot', 'Female', '8547.34', 'Marketing');
insert into employee (id, name, gender, salary, department) values (37, 'Weber Mitchard', 'Male', '5049.60', 'Engineering');
insert into employee (id, name, gender, salary, department) values (38, 'Micky Machent', 'Male', '4977.05', 'Marketing');
insert into employee (id, name, gender, salary, department) values (39, 'Valeria Doumerque', 'Female', '6933.48', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (40, 'Fleming Gingedale', 'Male', '5635.94', 'Support');
insert into employee (id, name, gender, salary, department) values (41, 'Maury Aristide', 'Male', '6398.86', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (42, 'Drugi Falck', 'Male', '8285.06', 'Support');
insert into employee (id, name, gender, salary, department) values (43, 'Van Lount', 'Male', '4350.54', 'Training');
insert into employee (id, name, gender, salary, department) values (44, 'Vick Darthe', 'Male', '8458.11', 'Training');
insert into employee (id, name, gender, salary, department) values (45, 'Archibaldo Spacy', 'Male', '5298.50', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (46, 'Angela Henden', 'Female', '6640.01', 'Accounting');
insert into employee (id, name, gender, salary, department) values (47, 'Aurelia Serjeant', 'Female', '6528.31', 'Business Development');
insert into employee (id, name, gender, salary, department) values (48, 'Shari Slimming', 'Female', '5259.69', 'Legal');
insert into employee (id, name, gender, salary, department) values (49, 'Jed Sent', 'Male', '7822.57', 'Training');
insert into employee (id, name, gender, salary, department) values (50, 'Robinet Litterick', 'Male', '7366.97', 'Product Management');
insert into employee (id, name, gender, salary, department) values (51, 'Waverly Frangleton', 'Male', '8685.34', 'Business Development');
insert into employee (id, name, gender, salary, department) values (52, 'Lezlie Lonnon', 'Female', '8887.03', 'Accounting');
insert into employee (id, name, gender, salary, department) values (53, 'Alejandro Marchbank', 'Genderfluid', '7351.04', 'Marketing');
insert into employee (id, name, gender, salary, department) values (54, 'Alair Ducker', 'Male', '6929.91', 'Marketing');
insert into employee (id, name, gender, salary, department) values (55, 'Caresse Capener', 'Female', '7504.07', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (56, 'Nikki Cowgill', 'Male', '7094.46', 'Business Development');
insert into employee (id, name, gender, salary, department) values (57, 'Hershel Sansun', 'Male', '8128.92', 'Engineering');
insert into employee (id, name, gender, salary, department) values (58, 'Laura Hackforth', 'Agender', '4694.03', 'Support');
insert into employee (id, name, gender, salary, department) values (59, 'Arliene Mooring', 'Female', '8197.51', 'Engineering');
insert into employee (id, name, gender, salary, department) values (60, 'Judye Kybird', 'Genderqueer', '6468.04', 'Marketing');
insert into employee (id, name, gender, salary, department) values (61, 'Anallese Woolmore', 'Female', '6620.76', 'Marketing');
insert into employee (id, name, gender, salary, department) values (62, 'Francis Gervaise', 'Male', '8669.71', 'Accounting');
insert into employee (id, name, gender, salary, department) values (63, 'Ebba Goodred', 'Female', '5442.78', 'Business Development');
insert into employee (id, name, gender, salary, department) values (64, 'Torrance Golightly', 'Male', '4112.69', 'Engineering');
insert into employee (id, name, gender, salary, department) values (65, 'Berry Pickett', 'Non-binary', '8189.15', 'Marketing');
insert into employee (id, name, gender, salary, department) values (66, 'Page D''Abbot-Doyle', 'Male', '7436.20', 'Accounting');
insert into employee (id, name, gender, salary, department) values (67, 'Ky Farington', 'Male', '7522.14', 'Business Development');
insert into employee (id, name, gender, salary, department) values (68, 'Rania Ferdinand', 'Female', '8020.17', 'Accounting');
insert into employee (id, name, gender, salary, department) values (69, 'Concordia Guillou', 'Female', '7047.22', 'Training');
insert into employee (id, name, gender, salary, department) values (70, 'Megan Fermin', 'Female', '4108.58', 'Legal');
insert into employee (id, name, gender, salary, department) values (71, 'Benoit Goodlud', 'Male', '8520.02', 'Product Management');
insert into employee (id, name, gender, salary, department) values (72, 'Linc Pagnin', 'Male', '7417.01', 'Sales');
insert into employee (id, name, gender, salary, department) values (73, 'Chilton Danbi', 'Male', '6729.61', 'Services');
insert into employee (id, name, gender, salary, department) values (74, 'Dewain Danielut', 'Male', '4337.03', 'Marketing');
insert into employee (id, name, gender, salary, department) values (75, 'Laurie Spratt', 'Genderqueer', '7583.75', 'Marketing');
insert into employee (id, name, gender, salary, department) values (76, 'Vikki Gerb', 'Female', '7693.46', 'Support');
insert into employee (id, name, gender, salary, department) values (77, 'Clywd Eyres', 'Male', '8961.22', 'Product Management');
insert into employee (id, name, gender, salary, department) values (78, 'Alli Leverage', 'Female', '6257.19', 'Product Management');
insert into employee (id, name, gender, salary, department) values (79, 'Lynsey Tute', 'Female', '7504.70', 'Training');
insert into employee (id, name, gender, salary, department) values (80, 'Carl Hiom', 'Male', '5210.23', 'Support');
insert into employee (id, name, gender, salary, department) values (81, 'Elianora Willard', 'Female', '5423.70', 'Business Development');
insert into employee (id, name, gender, salary, department) values (82, 'Keelby Hupe', 'Male', '7527.92', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (83, 'Salim Dowley', 'Male', '8346.43', 'Engineering');
insert into employee (id, name, gender, salary, department) values (84, 'Hobey Jennick', 'Male', '7472.13', 'Sales');
insert into employee (id, name, gender, salary, department) values (85, 'Durant Charrington', 'Male', '7034.95', 'Marketing');
insert into employee (id, name, gender, salary, department) values (86, 'Basilio Greenwood', 'Genderqueer', '4306.88', 'Engineering');
insert into employee (id, name, gender, salary, department) values (87, 'Mira Muris', 'Female', '5446.51', 'Legal');
insert into employee (id, name, gender, salary, department) values (88, 'Ailey Plak', 'Agender', '6262.60', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (89, 'Maryl Fallow', 'Female', '5505.85', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (90, 'Broderic Feak', 'Male', '6427.87', 'Engineering');
insert into employee (id, name, gender, salary, department) values (91, 'Ambrosio Durban', 'Male', '8898.62', 'Business Development');
insert into employee (id, name, gender, salary, department) values (92, 'Teresa Sandiford', 'Female', '5300.27', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (93, 'Ruby MacKereth', 'Male', '6626.20', 'Engineering');
insert into employee (id, name, gender, salary, department) values (94, 'Sosanna Dunster', 'Female', '4448.39', 'Product Management');
insert into employee (id, name, gender, salary, department) values (95, 'Dalia Birtles', 'Female', '6322.93', 'Engineering');
insert into employee (id, name, gender, salary, department) values (96, 'Webb Caulket', 'Male', '6546.22', 'Accounting');
insert into employee (id, name, gender, salary, department) values (97, 'Kali Yarr', 'Female', '4496.14', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (98, 'Deloria Allard', 'Female', '4784.78', 'Marketing');
insert into employee (id, name, gender, salary, department) values (99, 'Gaultiero Blogg', 'Male', '6046.98', 'Business Development');
insert into employee (id, name, gender, salary, department) values (100, 'Mattias Camier', 'Male', '7904.52', 'Training');
insert into employee (id, name, gender, salary, department) values (101, 'Tann Turfitt', 'Male', '7768.19', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (102, 'Trina Baudino', 'Female', '4431.99', 'Engineering');
insert into employee (id, name, gender, salary, department) values (103, 'Devin Arrowsmith', 'Agender', '7243.87', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (104, 'Phillipe Kohen', 'Male', '4576.82', 'Product Management');
insert into employee (id, name, gender, salary, department) values (105, 'Beulah Oliveras', 'Female', '6696.84', 'Business Development');
insert into employee (id, name, gender, salary, department) values (106, 'Caritta Bartlomiejczyk', 'Female', '6079.27', 'Business Development');
insert into employee (id, name, gender, salary, department) values (107, 'Aubrey Edess', 'Female', '5752.50', 'Product Management');
insert into employee (id, name, gender, salary, department) values (108, 'Roscoe Hadley', 'Bigender', '7115.90', 'Support');
insert into employee (id, name, gender, salary, department) values (109, 'Jorry Carriage', 'Female', '5794.79', 'Engineering');
insert into employee (id, name, gender, salary, department) values (110, 'Brinna Mower', 'Female', '4276.05', 'Support');
insert into employee (id, name, gender, salary, department) values (111, 'Chrysler Palin', 'Female', '8381.29', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (112, 'Jeanelle McHarry', 'Female', '4954.00', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (113, 'Binnie Ram', 'Female', '7879.99', 'Services');
insert into employee (id, name, gender, salary, department) values (114, 'Aldrich Skull', 'Male', '6900.82', 'Services');
insert into employee (id, name, gender, salary, department) values (115, 'Keelby Tomney', 'Male', '7691.25', 'Product Management');
insert into employee (id, name, gender, salary, department) values (116, 'Marsh Jedrysik', 'Male', '6602.27', 'Business Development');
insert into employee (id, name, gender, salary, department) values (117, 'Kirby Mahedy', 'Male', '6989.64', 'Product Management');
insert into employee (id, name, gender, salary, department) values (118, 'Alonso Featherby', 'Male', '7612.99', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (119, 'Vikky Sandlin', 'Female', '7723.19', 'Engineering');
insert into employee (id, name, gender, salary, department) values (120, 'Tomas Wadesworth', 'Male', '8143.15', 'Engineering');
insert into employee (id, name, gender, salary, department) values (121, 'Lola Divine', 'Female', '7309.01', 'Sales');
insert into employee (id, name, gender, salary, department) values (122, 'Maryl Rosewarne', 'Female', '7477.20', 'Training');
insert into employee (id, name, gender, salary, department) values (123, 'Mable Goligly', 'Female', '7357.82', 'Engineering');
insert into employee (id, name, gender, salary, department) values (124, 'Joanna Warnock', 'Female', '6072.17', 'Sales');
insert into employee (id, name, gender, salary, department) values (125, 'Vinnie Sirkett', 'Female', '8901.56', 'Legal');
insert into employee (id, name, gender, salary, department) values (126, 'Debby McGibbon', 'Female', '7917.44', 'Sales');
insert into employee (id, name, gender, salary, department) values (127, 'Matteo Rouby', 'Agender', '7926.37', 'Training');
insert into employee (id, name, gender, salary, department) values (128, 'Marcelle January 1st', 'Female', '5762.21', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (129, 'Jourdan O''Kane', 'Female', '6690.41', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (130, 'Elberta Dumblton', 'Female', '7074.90', 'Sales');
insert into employee (id, name, gender, salary, department) values (131, 'Niki Menier', 'Female', '6564.24', 'Training');
insert into employee (id, name, gender, salary, department) values (132, 'Aldwin Cormode', 'Male', '4788.23', 'Training');
insert into employee (id, name, gender, salary, department) values (133, 'Yancey Haw', 'Male', '5222.59', 'Services');
insert into employee (id, name, gender, salary, department) values (134, 'Clare Phillput', 'Female', '5635.17', 'Legal');
insert into employee (id, name, gender, salary, department) values (135, 'Talia Kiledal', 'Genderqueer', '7992.62', 'Marketing');
insert into employee (id, name, gender, salary, department) values (136, 'Oralie Teasell', 'Female', '7967.61', 'Sales');
insert into employee (id, name, gender, salary, department) values (137, 'Brier O''Kielt', 'Female', '5114.44', 'Services');
insert into employee (id, name, gender, salary, department) values (138, 'Karmen Spratt', 'Female', '8688.50', 'Marketing');
insert into employee (id, name, gender, salary, department) values (139, 'Arlie Stiell', 'Female', '7719.83', 'Accounting');
insert into employee (id, name, gender, salary, department) values (140, 'Trueman Bleiman', 'Male', '7191.86', 'Business Development');
insert into employee (id, name, gender, salary, department) values (141, 'Dolli Kausche', 'Female', '7057.99', 'Marketing');
insert into employee (id, name, gender, salary, department) values (142, 'Ramsay Dunkerton', 'Male', '8407.23', 'Sales');
insert into employee (id, name, gender, salary, department) values (143, 'Marrilee Kilmurry', 'Female', '4698.20', 'Training');
insert into employee (id, name, gender, salary, department) values (144, 'Nappie Cortes', 'Male', '5495.25', 'Legal');
insert into employee (id, name, gender, salary, department) values (145, 'Dilan Morilla', 'Polygender', '8963.86', 'Support');
insert into employee (id, name, gender, salary, department) values (146, 'Lynnett Crickmoor', 'Genderfluid', '5174.42', 'Training');
insert into employee (id, name, gender, salary, department) values (147, 'Maude Sanzio', 'Female', '7777.22', 'Support');
insert into employee (id, name, gender, salary, department) values (148, 'Nigel Causley', 'Male', '7763.60', 'Services');
insert into employee (id, name, gender, salary, department) values (149, 'Gilberto Mattersley', 'Male', '8904.18', 'Product Management');
insert into employee (id, name, gender, salary, department) values (150, 'Hester MacDougall', 'Female', '5303.21', 'Product Management');
insert into employee (id, name, gender, salary, department) values (151, 'Renaud Avo', 'Male', '7286.58', 'Accounting');
insert into employee (id, name, gender, salary, department) values (152, 'Ilaire Aleksankov', 'Male', '8273.97', 'Sales');
insert into employee (id, name, gender, salary, department) values (153, 'Holly Gallifont', 'Female', '4588.82', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (154, 'Tuesday Gilvary', 'Female', '4031.79', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (155, 'Ag Drage', 'Female', '7794.16', 'Engineering');
insert into employee (id, name, gender, salary, department) values (156, 'Felix Gaspero', 'Male', '4563.04', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (157, 'Burgess Rittmeyer', 'Male', '8641.71', 'Engineering');
insert into employee (id, name, gender, salary, department) values (158, 'Devon Trevena', 'Female', '5728.54', 'Legal');
insert into employee (id, name, gender, salary, department) values (159, 'Shirley Sealand', 'Female', '7160.00', 'Product Management');
insert into employee (id, name, gender, salary, department) values (160, 'Waverley Quinnette', 'Male', '4915.55', 'Accounting');
insert into employee (id, name, gender, salary, department) values (161, 'Fran Climance', 'Female', '5696.67', 'Support');
insert into employee (id, name, gender, salary, department) values (162, 'Clementine Wallis', 'Female', '7426.12', 'Sales');
insert into employee (id, name, gender, salary, department) values (163, 'Addy Schild', 'Female', '5750.87', 'Accounting');
insert into employee (id, name, gender, salary, department) values (164, 'Normand Gylle', 'Non-binary', '7938.34', 'Support');
insert into employee (id, name, gender, salary, department) values (165, 'Belva Aizikovitz', 'Female', '7370.81', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (166, 'Cyndia D''Alessio', 'Female', '5892.33', 'Sales');
insert into employee (id, name, gender, salary, department) values (167, 'Bryce Crawley', 'Male', '7601.26', 'Legal');
insert into employee (id, name, gender, salary, department) values (168, 'Maxy Neligan', 'Female', '7937.38', 'Engineering');
insert into employee (id, name, gender, salary, department) values (169, 'Celestyna Sarfass', 'Female', '6372.67', 'Business Development');
insert into employee (id, name, gender, salary, department) values (170, 'Griz MacVagh', 'Male', '4313.53', 'Product Management');
insert into employee (id, name, gender, salary, department) values (171, 'Clay Haldin', 'Male', '8377.82', 'Product Management');
insert into employee (id, name, gender, salary, department) values (172, 'Iosep Kirrage', 'Male', '4030.58', 'Sales');
insert into employee (id, name, gender, salary, department) values (173, 'Gabriello Tarver', 'Male', '8683.97', 'Training');
insert into employee (id, name, gender, salary, department) values (174, 'Monte Taks', 'Male', '4837.49', 'Training');
insert into employee (id, name, gender, salary, department) values (175, 'Trude Dudson', 'Female', '6334.96', 'Legal');
insert into employee (id, name, gender, salary, department) values (176, 'Colette Mizzen', 'Female', '5364.74', 'Business Development');
insert into employee (id, name, gender, salary, department) values (177, 'Winifield Klesel', 'Male', '8953.85', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (178, 'Terrill Bockh', 'Male', '4359.91', 'Marketing');
insert into employee (id, name, gender, salary, department) values (179, 'Reba Arnley', 'Female', '4834.09', 'Sales');
insert into employee (id, name, gender, salary, department) values (180, 'Kassie Dufty', 'Female', '5473.84', 'Accounting');
insert into employee (id, name, gender, salary, department) values (181, 'Delaney Dockwra', 'Male', '8545.32', 'Business Development');
insert into employee (id, name, gender, salary, department) values (182, 'Langston Cobbald', 'Male', '7551.51', 'Product Management');
insert into employee (id, name, gender, salary, department) values (183, 'Stanwood Vautrey', 'Male', '6345.75', 'Accounting');
insert into employee (id, name, gender, salary, department) values (184, 'Nana Threadkell', 'Female', '8877.48', 'Marketing');
insert into employee (id, name, gender, salary, department) values (185, 'Rosita Dudny', 'Female', '8201.14', 'Accounting');
insert into employee (id, name, gender, salary, department) values (186, 'Nixie Ramshaw', 'Female', '5861.71', 'Product Management');
insert into employee (id, name, gender, salary, department) values (187, 'Tedi Guerner', 'Female', '6439.76', 'Marketing');
insert into employee (id, name, gender, salary, department) values (188, 'Frederigo Filoniere', 'Male', '5425.29', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (189, 'Symon Booker', 'Male', '7067.12', 'Services');
insert into employee (id, name, gender, salary, department) values (190, 'Crista Czaple', 'Female', '5051.07', 'Business Development');
insert into employee (id, name, gender, salary, department) values (191, 'Aylmar Conlon', 'Male', '8104.75', 'Training');
insert into employee (id, name, gender, salary, department) values (192, 'Mitchael Tullot', 'Male', '5374.09', 'Legal');
insert into employee (id, name, gender, salary, department) values (193, 'Drake Stanislaw', 'Male', '4446.50', 'Support');
insert into employee (id, name, gender, salary, department) values (194, 'Guglielmo Flecknoe', 'Male', '8498.47', 'Legal');
insert into employee (id, name, gender, salary, department) values (195, 'Giorgia Sneezem', 'Bigender', '4740.47', 'Sales');
insert into employee (id, name, gender, salary, department) values (196, 'Amby Riguard', 'Male', '8231.35', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (197, 'Dorree Harpham', 'Female', '5937.57', 'Engineering');
insert into employee (id, name, gender, salary, department) values (198, 'Elisabeth Stallwood', 'Female', '6378.63', 'Marketing');
insert into employee (id, name, gender, salary, department) values (199, 'Eddie Elgie', 'Female', '4956.16', 'Support');
insert into employee (id, name, gender, salary, department) values (200, 'Vassily Lunney', 'Male', '6917.83', 'Services');
insert into employee (id, name, gender, salary, department) values (201, 'Bo Mc Gee', 'Male', '6328.53', 'Support');
insert into employee (id, name, gender, salary, department) values (202, 'Mercie Albiston', 'Female', '5590.60', 'Legal');
insert into employee (id, name, gender, salary, department) values (203, 'Bartlett Opfer', 'Genderqueer', '5296.05', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (204, 'Leslie Lannin', 'Male', '5715.52', 'Business Development');
insert into employee (id, name, gender, salary, department) values (205, 'Hymie Ibotson', 'Male', '7321.71', 'Support');
insert into employee (id, name, gender, salary, department) values (206, 'Booth Saunter', 'Genderqueer', '5768.62', 'Marketing');
insert into employee (id, name, gender, salary, department) values (207, 'Ardelle Casini', 'Female', '5807.72', 'Legal');
insert into employee (id, name, gender, salary, department) values (208, 'Bianca Chadney', 'Female', '6161.75', 'Legal');
insert into employee (id, name, gender, salary, department) values (209, 'Jasmina Vakhlov', 'Female', '4009.10', 'Accounting');
insert into employee (id, name, gender, salary, department) values (210, 'Randolf Northcliffe', 'Agender', '7174.22', 'Support');
insert into employee (id, name, gender, salary, department) values (211, 'Merrilee Frances', 'Female', '5952.34', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (212, 'Micheal Ure', 'Male', '8867.32', 'Training');
insert into employee (id, name, gender, salary, department) values (213, 'Wallie Yearnsley', 'Male', '8526.81', 'Legal');
insert into employee (id, name, gender, salary, department) values (214, 'Clea Boothebie', 'Female', '4742.76', 'Engineering');
insert into employee (id, name, gender, salary, department) values (215, 'Rena Stobo', 'Female', '8282.67', 'Engineering');
insert into employee (id, name, gender, salary, department) values (216, 'Lorianne Venturoli', 'Female', '6505.98', 'Sales');
insert into employee (id, name, gender, salary, department) values (217, 'Jean Soda', 'Male', '5822.51', 'Marketing');
insert into employee (id, name, gender, salary, department) values (218, 'Teador Hann', 'Male', '7349.65', 'Product Management');
insert into employee (id, name, gender, salary, department) values (219, 'Nelly MacWhan', 'Female', '7950.57', 'Support');
insert into employee (id, name, gender, salary, department) values (220, 'Rey Leadbitter', 'Female', '4222.72', 'Support');
insert into employee (id, name, gender, salary, department) values (221, 'Melva Seabon', 'Female', '7370.48', 'Marketing');
insert into employee (id, name, gender, salary, department) values (222, 'Guenna Willman', 'Female', '4548.08', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (223, 'Jethro Gabey', 'Genderqueer', '6728.36', 'Accounting');
insert into employee (id, name, gender, salary, department) values (224, 'Bank Tembridge', 'Genderfluid', '4656.85', 'Support');
insert into employee (id, name, gender, salary, department) values (225, 'Margalit Condy', 'Female', '5196.49', 'Engineering');
insert into employee (id, name, gender, salary, department) values (226, 'Lindon Loton', 'Male', '7814.88', 'Business Development');
insert into employee (id, name, gender, salary, department) values (227, 'Paddie Biasetti', 'Male', '8273.51', 'Product Management');
insert into employee (id, name, gender, salary, department) values (228, 'Alfy Barens', 'Female', '7228.16', 'Legal');
insert into employee (id, name, gender, salary, department) values (229, 'Thedrick Kernock', 'Male', '6241.87', 'Support');
insert into employee (id, name, gender, salary, department) values (230, 'Marlyn Neagle', 'Agender', '6517.58', 'Support');
insert into employee (id, name, gender, salary, department) values (231, 'Betteann Wanless', 'Female', '6974.92', 'Sales');
insert into employee (id, name, gender, salary, department) values (232, 'Bunni Gwilliam', 'Female', '4211.80', 'Sales');
insert into employee (id, name, gender, salary, department) values (233, 'Karole Quiddihy', 'Female', '6881.12', 'Support');
insert into employee (id, name, gender, salary, department) values (234, 'Rikki Sargison', 'Male', '7350.21', 'Services');
insert into employee (id, name, gender, salary, department) values (235, 'Nickolaus Commings', 'Male', '5821.38', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (236, 'Jobyna Marler', 'Female', '5652.25', 'Accounting');
insert into employee (id, name, gender, salary, department) values (237, 'Tanitansy Poser', 'Female', '4922.59', 'Product Management');
insert into employee (id, name, gender, salary, department) values (238, 'Cordey Wathall', 'Female', '6212.35', 'Business Development');
insert into employee (id, name, gender, salary, department) values (239, 'Rand Toderi', 'Agender', '4300.19', 'Sales');
insert into employee (id, name, gender, salary, department) values (240, 'Poppy Sargeaunt', 'Female', '6124.66', 'Product Management');
insert into employee (id, name, gender, salary, department) values (241, 'Elisabetta Sukbhans', 'Female', '4425.95', 'Legal');
insert into employee (id, name, gender, salary, department) values (242, 'Camel Galloway', 'Female', '7026.35', 'Sales');
insert into employee (id, name, gender, salary, department) values (243, 'Odette Saffin', 'Female', '8841.12', 'Engineering');
insert into employee (id, name, gender, salary, department) values (244, 'Luciano Rubinek', 'Male', '8225.59', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (245, 'Tiphany Bryett', 'Polygender', '6948.74', 'Engineering');
insert into employee (id, name, gender, salary, department) values (246, 'Ansell Caswall', 'Male', '6681.22', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (247, 'Bette-ann Bellard', 'Female', '8482.66', 'Legal');
insert into employee (id, name, gender, salary, department) values (248, 'Nathanial Cuseick', 'Male', '6840.87', 'Training');
insert into employee (id, name, gender, salary, department) values (249, 'Lizbeth Hoble', 'Female', '6759.82', 'Sales');
insert into employee (id, name, gender, salary, department) values (250, 'Jefferey Moxham', 'Male', '5869.53', 'Support');
insert into employee (id, name, gender, salary, department) values (251, 'Ninnetta Tilte', 'Female', '8125.87', 'Legal');
insert into employee (id, name, gender, salary, department) values (252, 'Pavia Beernaert', 'Female', '7209.25', 'Services');
insert into employee (id, name, gender, salary, department) values (253, 'Paxton Hefferon', 'Male', '6188.91', 'Product Management');
insert into employee (id, name, gender, salary, department) values (254, 'Raleigh Powner', 'Male', '7340.20', 'Product Management');
insert into employee (id, name, gender, salary, department) values (255, 'Diandra Risborough', 'Female', '4254.45', 'Marketing');
insert into employee (id, name, gender, salary, department) values (256, 'Killy Cronshaw', 'Male', '4251.02', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (257, 'Kipper Storrah', 'Male', '6552.28', 'Training');
insert into employee (id, name, gender, salary, department) values (258, 'Shoshanna Musto', 'Agender', '4239.34', 'Product Management');
insert into employee (id, name, gender, salary, department) values (259, 'Rabi Storror', 'Male', '6546.57', 'Marketing');
insert into employee (id, name, gender, salary, department) values (260, 'Patten Dumphries', 'Male', '6897.35', 'Support');
insert into employee (id, name, gender, salary, department) values (261, 'Danie Allabarton', 'Male', '4319.09', 'Business Development');
insert into employee (id, name, gender, salary, department) values (262, 'Dalila Howsin', 'Agender', '6825.65', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (263, 'Albie Entissle', 'Male', '8424.95', 'Services');
insert into employee (id, name, gender, salary, department) values (264, 'Lorena De Bruijne', 'Female', '7699.99', 'Accounting');
insert into employee (id, name, gender, salary, department) values (265, 'Suzanne Mannooch', 'Polygender', '7672.94', 'Marketing');
insert into employee (id, name, gender, salary, department) values (266, 'Nanette Treslove', 'Female', '6729.04', 'Support');
insert into employee (id, name, gender, salary, department) values (267, 'Abby Devonald', 'Female', '7735.49', 'Accounting');
insert into employee (id, name, gender, salary, department) values (268, 'Cornall Cadigan', 'Male', '7864.28', 'Product Management');
insert into employee (id, name, gender, salary, department) values (269, 'Fawne Waith', 'Female', '8287.37', 'Product Management');
insert into employee (id, name, gender, salary, department) values (270, 'Cornelia Aldridge', 'Female', '7214.64', 'Legal');
insert into employee (id, name, gender, salary, department) values (271, 'Gabbie Forde', 'Male', '5663.19', 'Accounting');
insert into employee (id, name, gender, salary, department) values (272, 'Brigitte Darker', 'Female', '5291.10', 'Sales');
insert into employee (id, name, gender, salary, department) values (273, 'Loralie Turford', 'Female', '8737.41', 'Product Management');
insert into employee (id, name, gender, salary, department) values (274, 'Collie Tebbit', 'Agender', '4192.54', 'Support');
insert into employee (id, name, gender, salary, department) values (275, 'Rosene Ebbens', 'Female', '7235.19', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (276, 'Belva Braddick', 'Female', '6063.55', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (277, 'Hermie Snasel', 'Male', '5251.04', 'Product Management');
insert into employee (id, name, gender, salary, department) values (278, 'Niels Baltrushaitis', 'Agender', '4280.05', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (279, 'Francisco Steel', 'Male', '6752.01', 'Accounting');
insert into employee (id, name, gender, salary, department) values (280, 'Westbrook Jope', 'Male', '8137.66', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (281, 'Mignon Allender', 'Female', '4673.02', 'Training');
insert into employee (id, name, gender, salary, department) values (282, 'Edd Kelleway', 'Male', '5886.56', 'Engineering');
insert into employee (id, name, gender, salary, department) values (283, 'Adolf Clineck', 'Male', '6835.98', 'Accounting');
insert into employee (id, name, gender, salary, department) values (284, 'Ulrikaumeko Olekhov', 'Female', '4335.59', 'Legal');
insert into employee (id, name, gender, salary, department) values (285, 'Livvyy Flowers', 'Bigender', '8602.18', 'Services');
insert into employee (id, name, gender, salary, department) values (286, 'Hamil Iscowitz', 'Male', '5962.79', 'Legal');
insert into employee (id, name, gender, salary, department) values (287, 'Flory Gianiello', 'Male', '4019.61', 'Services');
insert into employee (id, name, gender, salary, department) values (288, 'Arabella Blaymires', 'Female', '4706.76', 'Business Development');
insert into employee (id, name, gender, salary, department) values (289, 'Rudd Hulance', 'Male', '6791.95', 'Legal');
insert into employee (id, name, gender, salary, department) values (290, 'Granny Shiels', 'Male', '8473.18', 'Product Management');
insert into employee (id, name, gender, salary, department) values (291, 'Hubert Pickthorne', 'Agender', '5217.75', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (292, 'Rosy Dows', 'Bigender', '8084.59', 'Support');
insert into employee (id, name, gender, salary, department) values (293, 'Jeremias Jerman', 'Male', '8798.66', 'Human Resources');
insert into employee (id, name, gender, salary, department) values (294, 'Skippie Dwine', 'Male', '4680.14', 'Research and Development');
insert into employee (id, name, gender, salary, department) values (295, 'Oberon Beveredge', 'Male', '8820.12', 'Engineering');
insert into employee (id, name, gender, salary, department) values (296, 'Katleen Code', 'Female', '8477.58', 'Training');
insert into employee (id, name, gender, salary, department) values (297, 'Arly Dracey', 'Female', '8216.63', 'Marketing');
insert into employee (id, name, gender, salary, department) values (298, 'Bernadina Matthius', 'Female', '6318.21', 'Human Resources');